### PR TITLE
fixed issues with status closes #500 #501 #502

### LINKED ISSUE #500: Bug: Core crashing
I found the below bug in core when sending through a transaction: Core crashes when it doesnt find response.timestamp. Could potential be due to a mediator error being used but core error should be handled
screenshot from 2015-05-25 16 23 18

### PR DESCRIPTION
**Pull request by debonair**
@devcritter please review

### CODE REVIEW

File: src/middleware/messageStore.coffee [hunk 1]
```diff
@@ -122,32 +126,38 @@ exports.setFinalStatus = setFinalStatus = (ctx, callback) ->
...
-    # In all other cases mark as completed
-    if ctx.status is null or ctx.status is undefined
-      tx.status = transactionStatus.COMPLETED
-
-    logger.info "Final status for transaction #{tx._id} : #{tx.status}"
-    transactions.Transaction.findByIdAndUpdate transactionId, {status: tx.status}, { },  (err,tx) ->
-      tx.save
-      callback tx
+      # In all other cases mark as completed
+      if ctx.status is null or ctx.status is undefined
```
Comment (devcritter) [inline src/middleware/messageStore.coffee]: Could probably just say: `if not ctx.status`

**Comment by devcritter** [comment]
Thanks @debonair! Looks good. Just one very minor comment but otherwise :+1: I tested against the mediator and solves the issues.
